FROM node@sha256:bac289a6f393990e759c672d5f567553c697255d1fb858e2c62d086a2dfae44a AS node

WORKDIR /app

ENV NODE_ENV production
COPY package.json yarn.lock ./

# install dev dependencies too
RUN set -x && yarn --prod=false

COPY . .
RUN set -x && yarn run prestart:prod

EXPOSE 3000

CMD [ "node", "dist/main.js" ]
