version: '2'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-prod
    container_name: app
    depends_on:
      - postgres
      - redis
    volumes:
      - .env:/app/.env
      - ./logs:/app/logs
      - ./data:/app/data
    environment:
      fileExt: js

  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    container_name: app-nginx
    depends_on:
      - app
    environment:
      - NGINX_SERVER_NAME=localhost
      - NEST_HOST=app
      - NEST_PORT=3000
      - NGINX_MAX_BODY=100M
    ports:
      - 80:80

  postgres:
    image: postgres
    container_name: app-postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - ./postgres-data:/var/lib/postgresql
    ports:
      - 5433:5432
  redis:
    image: redis
    container_name: app-redis
    ports:
      - 6380:6379
    command: redis-server --requirepass ${REDIS_PASSWOR}
# volumes:
#   postgresdbdata:-
